### PR TITLE
Exposes the ability to query/force the root window focus #82

### PR DESCRIPTION
**Pull request by justledbetter**
Working on trying to get to the bottom of the root focus issue, and figured exposing these features via nucular.Window might be a good idea (but always happy to defer to your guidance if not!)  😅

### CODE REVIEW

**Comment by aarzilli** [comment]
ActivateWindow should also work with the root window and you can check if a window has focus by calling `Input`

**Comment by justledbetter** [comment]
Got it, makes sense!

I'm having trouble getting this to work in my application, but suspect it's an issue with the way I'm trying to handle "global" keystrokes.  Working on poking things to see if I can make it work as expected 😁

**Comment by justledbetter** [comment]
Question regarding Window.Input() - Its behavior appears to be governed by Window.toplevel() (https://github.com/aarzilli/nucular/blob/4e84d707c90235ee7b4fef22c1260a7b0b2e9526/input.go#L125), specifically `win.idx == win.ctx.floatWindowFocus`.

Does this account for when the MasterWindow is in focus?  (On second thought, it seems win.idx should be 0 when we're looking at the MasterWindow's handle, so this may be barking up the wrong tree :) )

**Comment by aarzilli** [comment]
Yes, when rootWindowFocus is true floatWindowFocus is zero and toplevel returns true.

**Pull request closed without merging**
