### PR TITLE
Adds more control over window title bar color (labels and states)

### PR DESCRIPTION
**Pull request by justledbetter**
This change adds the ability to control window header background and label colors via `style.ColorTable`, and expands the initialization of `style.defaultThemeTable` so it's easier to add other elements in the future (if the need arises).

Also want to allow the user control over the main window background, but not familiar enough with the codebase to do that yet.  Will submit another PR if I get it figured out!

Really love what you've done with the project so far, hope this is at least a little helpful!

### CODE REVIEW

**Review by aarzilli — COMMENTED** [review]
This change breaks the red, dark and white themes because you didn't update their tables and the code doesn't fallback nicely if the new struct members aren't set.

It's also a questionable change in terms of functionality. The ColorTable method of setting up a style is not meant to be fully exhaustive, there's a lot of fields of `Style` that it doesn't let you set individually. If clients need to change those they can always change the `Style` struct after initializing it with a ColorTable.

I hard for me to me why these fileds, related to the window header, in particular merit to be in the ColorTable.

**Comment by justledbetter** [comment]
Thought I did update the other themes with these new colors - see for example https://github.com/justledbetter/nucular/blob/74d539c93b742365d19e6b7c10b392a04f01199f/style/style.go#L1008

The only reason I thought of adding the Header label text color to the ColorTable is so that they can be set at the same time as the Header background color - otherwise the codebase seems to default to black text even when a dark background color is selected.  (I added the Highlight state colors at the same time, since I happened to be in the same neighborhood of the code).

If there's a better way I should be initializing the app with a custom theme and this is ultimately unnecessary, happy to withdraw the PR - Just let me know what I *should* be doing!  :)

**Comment by aarzilli** [comment]
> If there's a better way I should be initializing the app with a custom theme and this is ultimately unnecessary, happy to withdraw the PR - Just let me know what I should be doing! :)

ColorTable is a convenient way of setting up a theme, but it doesn't expose all of the underlying attributes of the Style struct. If it doesn't satisfy your needs you can just change the Style fields directly. For example suppose you want the dark theme but with the title text orange for inactive windows:

```
package main

import (
	"image/color"

	"github.com/aarzilli/nucular"
	"github.com/aarzilli/nucular/rect"
	nstyle "github.com/aarzilli/nucular/style"
)

func main() {
	Wnd := nucular.NewMasterWindow(0, "Example", func(w *nucular.Window) {})
	Wnd.PopupOpen("Example 1", nucular.WindowTitle|nucular.WindowBorder|nucular.WindowMovable|nucular.WindowScalable|nucular.WindowNonmodal, rect.Rect{0, 0, 400, 300}, true, func(w *nucular.Window) {
	})
	Wnd.PopupOpen("Example 2", nucular.WindowTitle|nucular.WindowBorder|nucular.WindowMovable|nucular.WindowScalable|nucular.WindowNonmodal, rect.Rect{0, 0, 400, 300}, true, func(w *nucular.Window) {
	})
	Wnd.SetStyle(nstyle.FromTheme(nstyle.DarkTheme, 2.0))
	style := Wnd.Style()
	style.NormalWindow.Header.LabelNormal = color.RGBA{ 255,165,0, 255 }
	Wnd.Main()
}
```

**Comment by justledbetter** [comment]
Makes sense, will adjust my code to behave like that.  Thanks for your patience!  😄

**Pull request closed without merging**
